# Generated by Django 3.1.4 on 2020-12-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_main', '0022_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
