# Generated by Django 3.1.4 on 2024-07-02 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_main', '0030_rules_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
