# Generated by Django 3.1.4 on 2024-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_main', '0033_auto_20240704_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
